# Generated by Django 4.1 on 2022-08-05 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Skills name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='User email')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('skill', models.ManyToManyField(blank=True, to='users.skill', verbose_name='Skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
