# Generated by Django 4.1 on 2022-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hard_skill',
            field=models.ManyToManyField(blank=True, related_name='hard_skill', to='users.skill', verbose_name='Skills'),
        ),
    ]
